version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      - package-ecosystem: 'npm'
        directory: '/'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
        target-branch: 'main'
