version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    target-branch: 'main'
groups:
  - package-ecosystem: 'npm'
    directory: '/'
    update-types: ['version-update:semver-minor', 'version-update:semver-patch']
