import pkg from './package.json' with { type: 'json' }
import createConfig from './rolldown'

export default createConfig(
  [...Object.keys(pkg.dependencies || {})],
  [
    'src/index.ts',
    'src/testing/index.ts',
    'src/types/*.ts',
    '!src/types/*.spec.ts',
    // Files moved from src/types/ to src/ (src/types/ now contains deprecated re-exports)
    'src/account-manager.ts',
    'src/account.ts',
    'src/algorand-client-transaction-creator.ts',
    'src/algorand-client-transaction-sender.ts',
    'src/algorand-client.ts',
    'src/amount.ts',
    'src/app-client.ts',
    'src/app-deployer.ts',
    'src/app-factory.ts',
    'src/app-manager.ts',
    'src/app-spec.ts',
    'src/app.ts',
    'src/asset-manager.ts',
    'src/async-event-emitter.ts',
    'src/client-manager.ts',
    'src/composer.ts',
    'src/config.ts',
    'src/debugging.ts',
    'src/dispenser-client.ts',
    'src/expand.ts',
    'src/indexer.ts',
    'src/kmd-account-manager.ts',
    'src/lifecycle-events.ts',
    'src/logging.ts',
    'src/logic-error.ts',
    'src/network-client.ts',
    // Package re-exports
    'src/abi/index.ts',
    'src/algo25/index.ts',
    'src/transact/index.ts',
    'src/transaction/index.ts',
    'src/algod-client/index.ts',
    'src/indexer-client/index.ts',
    'src/kmd-client/index.ts',
  ],
)
