/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

import type { SignedTransaction } from '@algorandfoundation/algokit-transact'
import type { ModelMetadata } from '../core/model-runtime'
import { getModelMeta, registerModelMeta } from '../core/model-runtime'
import type { BlockAppEvalDelta } from './block-app-eval-delta'

/**
 * SignedTxnInBlock is a SignedTransaction with additional ApplyData and block-specific metadata.
 */
export interface SignedTxnInBlock {
  signedTransaction: SignedTransaction
  logicSignature?: Record<string, unknown>
  closingAmount?: bigint
  assetClosingAmount?: bigint
  senderRewards?: bigint
  receiverRewards?: bigint
  closeRewards?: bigint
  evalDelta?: BlockAppEvalDelta
  configAsset?: bigint
  applicationId?: bigint
  hasGenesisId?: boolean
  hasGenesisHash?: boolean
}

export const SignedTxnInBlockMeta: ModelMetadata = {
  name: 'SignedTxnInBlock',
  kind: 'object',
  fields: [
    {
      name: 'signedTransaction',
      // flatten signed transaction fields into parent
      flattened: true,
      optional: false,
      nullable: false,
      type: { kind: 'codec', codecKey: 'SignedTransaction' },
    },
    { name: 'logicSignature', wireKey: 'lsig', optional: true, nullable: false, type: { kind: 'scalar' } },
    { name: 'closingAmount', wireKey: 'ca', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'assetClosingAmount', wireKey: 'aca', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'senderRewards', wireKey: 'rs', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'receiverRewards', wireKey: 'rr', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'closeRewards', wireKey: 'rc', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    {
      name: 'evalDelta',
      wireKey: 'dt',
      optional: true,
      nullable: false,
      type: { kind: 'model', meta: () => getModelMeta('BlockAppEvalDelta') },
    },
    { name: 'configAsset', wireKey: 'caid', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'applicationId', wireKey: 'apid', optional: true, nullable: false, type: { kind: 'scalar', isBigint: true } },
    { name: 'hasGenesisId', wireKey: 'hgi', optional: true, nullable: false, type: { kind: 'scalar' } },
    { name: 'hasGenesisHash', wireKey: 'hgh', optional: true, nullable: false, type: { kind: 'scalar' } },
  ],
}

registerModelMeta('SignedTxnInBlock', SignedTxnInBlockMeta)
