name: Pull Request

on:
  pull_request:
    branches: [main, decoupling]

permissions:
  contents: read

jobs:
  check-provenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check dependency provenance
        uses: danielroe/provenance-action@41bcc969e579d9e29af08ba44fcbfdf95cee6e6c # v0.1.1
        with:
          fail-on-downgrade: 'true'
          fail-on-provenance-change: 'true'

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run CI
        uses: ./.github/actions/ci
        with:
          node-version: 24.x
          commit-lint-from: ${{ github.event.pull_request.base.sha }}
          commit-lint-to: ${{ github.event.pull_request.head.sha }}

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: docs/package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install docs dependencies
        run: pnpm install --frozen-lockfile --dir docs

      - name: Verify documentation builds
        run: pnpm --dir docs build

  verify-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Start LocalNet
        run: |
          pipx install algokit
          algokit localnet start
          pnpm dlx wait-on tcp:4001 -t 30000

      - name: Install examples dependencies
        working-directory: examples
        run: pnpm install --frozen-lockfile

      - name: Verify all examples
        working-directory: examples
        run: ./verify-all.sh
