name: Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pull_request:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      node-version: 20.x
      run-commit-lint: true
      run-build: true
      audit-script: npm run audit
      test-script: npm run test -- --silent
      install-algokit: true

  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - name: Use Node.js 20.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 20.x
      - name: Check docs are up to date
        shell: bash
        run: |
          npm ci --ignore-scripts
          npm run generate:code-docs
          # Add untracked files as empty so they come up in diff
          git add -N .
          # Print changed files and error out if there are changes after generating docs
          git diff --exit-code --name-only
