name: Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@main
    with:
      run-commit-lint: true
      run-build: true
      audit-script: npm run audit
      test-script: npm run test -- --silent
      install-algokit: true
      polytest: false

  check-docs:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/check-docs.yml@main
