name: Publish

on:
  push:
    branches:
      - main
      - release
      - decoupling
  workflow_dispatch:

concurrency: release

permissions:
  contents: write
  issues: read
  id-token: write

jobs:
  ci:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-ci.yml@chore/node-npm
    with:
      run-commit-lint: true
      run-build: true
      audit-script: npm run audit
      test-script: npm run test -- --silent
      install-algokit: true
      setup-polytest: true
      polytest-validate-script: npm run polytest:validate-algod
      polytest-generate-script: npm run polytest:generate
      polytest-generate-working-directory: packages/transact
      run-mock-servers: true

  check_docs:
    uses: algorandfoundation/algokit-shared-config/.github/workflows/check-docs.yml@chore/node-npm

  build:
    name: Build
    needs:
      - ci
      - check_docs
    uses: algorandfoundation/algokit-shared-config/.github/workflows/node-build-zip.yml@chore/node-npm
    with:
      build-path: dist
      artifact-name: package

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v3
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Set Git user as GitHub actions
        run: git config --global user.email "179917785+engineering-ci[bot]@users.noreply.github.com" && git config --global user.name "engineering-ci[bot]"

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Download built package
        uses: actions/download-artifact@v8
        with:
          name: package
          path: artifacts

      - name: Unzip package
        shell: bash
        run: |
          mkdir -p dist
          unzip -q "artifacts/package.zip" -d dist

      - name: Install dependencies to get semantic release components and plugins
        run: npm ci --ignore-scripts

      - name: 'Semantic release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}

  publish_docs:
    needs:
      - ci
      - check_docs
    if: github.ref == 'refs/heads/release'
    uses: algorandfoundation/algokit-shared-config/.github/workflows/publish-docs.yml@chore/node-npm
