name: Add comment to GitHub issue on Zendesk ticket commented
on:
  repository_dispatch:
    types:
      - zendesk_github_add_comment
permissions:
  issues: write
jobs:
  add-comment:
    name: Add comment to issue
    uses: algorandfoundation/gh_zendesk_sync/.github/workflows/zendesk_github_add_comment.yml@main
